config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root "pages#home"

  get "about" => "pages#about"

  get "pricing" => "pages#pricing"

  get "contact" => "pages#contact"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
	  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
	    user.email = auth.info.email
	    user.password = Devise.friendly_token[0,20]
	    user.name = auth.info.name   # assuming the user model has a name
  	end
	end
	  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about 
	end 
	
	def pricing 
	end
	
	def contact 
	end  
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
	def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
       <%= link_to "Parking Pro", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">  
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About us", about_path %></li>
        <li><%= link_to "Pricing", pricing_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Account Settings", edit_user_registration_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Parkingpro</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<div class="container">
		<% flash.each do |name, msg| %>
		     <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
		<% end %>
	<%= yield %>
</div>
</body>
</html>

app/views/pages/about.html.erb
<div class="center">

	<h1>About Us</h1>
	<p>We provide valet service around your city and you can pay directly through the app.</p>

</div>

app/views/pages/contact.html.erb
<div class="center">
	<h1>Contact us</h1>
	<p>Call us on +91xxxxxxx or mail us at user.email@email.com</p>
	
			<% if user_signed_in? %>
         Find the closest parking assistants. 
     	<% else %>
			<%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook)%>
    <% end %>  
			
</div>

app/views/pages/home.html.erb
<div class="center">
	<h1>Hello</h1>
	<p>Welcome to the solution for your parking problems. Sign up today to find out more.</p>
		<% if user_signed_in? %>
         Find the closest parking assistants. 
     <% else %>
			<%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
      <%= link_to "Sign up",new_user_registration_path, class: "btn btn-primary btn-lg" %>
    <% end %>  
</div>

app/views/pages/pricing.html.erb
<div class="center">
  
	<h1>Simple Pricing</h1>
	<p>We charge a standard price of Rupees 20 per hour plus a convenience fee. </p>
</br>
</div>